파이썬 장기 게임
hyu-barami/hyu-barami.github.io pull request #124
Opened 2022-12-01 15:33 UTC by jhg666

신규 포스트: 2022 전시회 작품 - 파이썬 장기 게임

2022-12-01 15:41 UTC, Dictor requested changes
누락된 부분 체크해서 커밋해주세요!!

2022-12-01 15:41 UTC, Dictor commented on _posts/2022-12-01-python-jangi.md
> +tags: [post,heyongyu,about-post]     # TAG names should always be lowercase, 띄어쓰기도 금지
about-post는 지워야합니다.

2022-12-01 15:41 UTC, Dictor commented on _posts/2022-12-01-python-jangi.md
> +세부적인 코드는 이 링크로 가시면 나옵니다: <https://github.com/jhg666/mini_jangi>
꺾쇠 말고 마크다운 링크 거는법으로 걸어야해요.

2022-12-01 15:41 UTC, Dictor commented on _posts/2022-12-01-python-jangi.md
> +<img src="/assets/img/post/2022-12-01-python-jangi/jangiresult.png">
이미지 파일도 커밋해주셔야 해요. 빠졌네요.

2022-12-01 16:47 UTC, jhg666 commented on _posts/2022-12-01-python-jangi.md
> +<img src="/assets/img/post/2022-12-01-python-jangi/jangiresult.png">
다 해결했습니다.

2022-12-02 12:58 UTC, Dictor commented
모두 해결된 것 확인했습니다.

2022-12-02 12:58 UTC, Dictor approved these changes

2022-12-02 12:58 UTC, merged