ADD: 12-04-circuit-programmer
hyu-barami/hyu-barami.github.io pull request #130
Opened 2022-12-03 17:06 UTC by Park-Hyung-Joo

2022-12-04-circuit-prorammer 추가

2022-12-03 17:57 UTC, kyaryunha requested changes

2022-12-03 17:57 UTC, kyaryunha commented on _posts/2022-12-04-circuit-programmer.md
> +tags: [post,hyungjoo,dongseon,changjo,choihyunseo,about-post]     # TAG names should always be lowercase, 띄어쓰기도 금지
about-post 빼주세요. 
about-post 는 
https://hyu-barami.github.io/tags/about-post/  에서 포스트 작성법에 관한 것을 모아놓기 위해 적은 태그입니다. (누가 잘못 머지했는지 이상한 글이 하나 껴있는데 수정 예정...)

2022-12-03 17:57 UTC, kyaryunha requested changes
적어 놓은 내용 반영해서 다시 커밋하고 푸시해주세요!
(참고용) 풀리퀘스트가 오픈되어 있으면, 커밋하고 푸시하면 풀리퀘스트에도 바로 반영됩니다!

2022-12-05 03:58 UTC, Park-Hyung-Joo commented
태그 지우고 푸시 다시했어 확인 부탁.

2022-12-06 08:08 UTC, kyaryunha approved these changes

2022-12-06 08:09 UTC, merged