picture
hyu-barami/hyu-barami.github.io pull request #97
Opened 2021-11-30 12:19 UTC by KDW1007

netflix picture

2021-11-30 12:25 UTC, Dictor requested changes
파일 경로가 `assets/img/post/스크린샷 2021-11-30 오후 9.12.52.png` 가 아닌 `assets/img/post/<게시물 파일명>/스크린샷 2021-11-30 오후 9.12.52.png`이 되어야해요. 다른분들이 하신 구조 참고하시면 좋을거 같아요. 그리고 사진 파일만 올라왔는데 마크다운상에서 해당 파일을 사용하는 부분은 이미 있나요?

2021-11-30 12:25 UTC, Dictor commented
리뷰 확인하시고 수정해서 다시 PR 부탁드립니다!!

2021-11-30 12:32 UTC, KDW1007 commented
글도 적었는데 안뜨나요?

2021년 11월 30일 (화) 오후 9:26, JeongHyun Kim ***@***.***>님이 작성:

> Closed #97 <https://github.com/hyu-barami/hyu-barami.github.io/pull/97>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hyu-barami/hyu-barami.github.io/pull/97#event-5691626081>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUZRWWTV5NITPCEY3UGZVCTUOS7HXANCNFSM5JBVCCFA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2022-01-11 15:39 UTC, Dictor commented
직권으로 포스트 수정하려 했으나 글이 올라오지 않은것 재확인

2022-01-11 15:39 UTC, closed without merging